# connect to the service Registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

      
# security
okta:
  oauth2:
    issuer: https://dev-37293701.okta.com/oauth2/default
    audience: api://default
